<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.daveysolutions</groupId>
    <artifactId>davey-scaffolding-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>
        <logstash.logback.encoder.version>7.4</logstash.logback.encoder.version>
        <spring-boot.version>3.3.13</spring-boot.version>
        <jib.base.image>eclipse-temurin:21.0.7_6-jre</jib.base.image>
        <spring.profiles.active>prod</spring.profiles.active>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>services/auth-service</module>
        <module>services/job-service</module>
        <module>gateway</module>
    </modules>
</project>
