spring.datasource.url=jdbc:postgresql://postgres:5432/users_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=auth_user
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
