spring.datasource.url=jdbc:postgresql://postgres:5432/jobs_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=jobs_user
spring.datasource.password=${JOBS_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
