spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: job-service
          uri: ${JOB_SERVICE_URI:http://job-service:8080}
          predicates:
            - Path=/api/v1/jobs/**

        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://auth-service:8080}
          predicates:
            - Path=/api/v1/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
